[alias]
t = "test"
tf = "test --features image"
tr = "test --release"
trf = "test --release --features image"

b = "build"
bf = "build --features image"
br = "build --release"
brf = "build --release --features image"

r = "run"
rf = "run --features image"
rr = "run --release"
rrf = "run --release --features image"

c = "check"
cf = "check --features image"
cr = "check --release"
crf = "check --release --features image"

d = "doc"
rm = "remove"
e_load_image = "run --example load-image"

# Windows
# [target.x86_64-pc-windows-msvc]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]
# [target.x86_64-pc-windows-gnu]
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]

# # On Linux:
# - Ubuntu, `sudo apt-get install lld clang`
# - Arch, `sudo pacman -S lld clang`
# [target.x86_64-unknown-linux-gnu]
# rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]

# # On MacOS, `brew install michaeleisel/zld/zld`
# [target.x86_64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld"]
# [target.aarch64-apple-darwin]
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/local/bin/zld"]
